import { Injectable, Logger } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import PDFDocument from 'pdfkit';
import * as fs from 'fs';
import * as path from 'path';
import { Incident, IncidentDocument } from '../../common/schemas/incident.schema';
import { Client, ClientDocument } from '../../common/schemas/client.schema';

/**
 * Feature 8: Compliance Incident Logging
 * Generates comprehensive compliance reports with incident data
 */
@Injectable()
export class ComplianceReportService {
  private readonly logger = new Logger(ComplianceReportService.name);
  private uploadsDir = process.env.UPLOADS_DIR || './uploads/compliance';

  constructor(
    @InjectModel(Incident.name) private incidentModel: Model<IncidentDocument>,
    @InjectModel(Client.name) private clientModel: Model<ClientDocument>,
  ) {
    // Ensure uploads directory exists
    if (!fs.existsSync(this.uploadsDir)) {
      fs.mkdirSync(this.uploadsDir, { recursive: true });
    }
  }

  /**
   * Download compliance report as PDF
   */
  async downloadComplianceReport(
    projectId: string,
    startDate: Date,
    endDate: Date,
  ): Promise<Buffer> {
    try {
      this.logger.debug(`Generating compliance report for ${projectId}`);

      // Fetch incidents in date range
      const incidents = await this.incidentModel
        .find({
          projectId,
          detectedAt: {
            $gte: startDate,
            $lte: endDate,
          },
        })
        .sort({ detectedAt: -1 })
        .lean();

      // Fetch client info
      const client = await this.clientModel.findById(projectId).lean();

      // Generate PDF
      const pdfBuffer = await this.generateCompliancePDF(client, incidents, startDate, endDate);

      this.logger.debug(`Compliance report generated with ${incidents.length} incidents`);
      return pdfBuffer;
    } catch (error) {
      const err = error as Error;
      this.logger.error(`Failed to generate compliance report: ${err.message}`);
      throw error;
    }
  }

  /**
   * Generate compliance PDF document
   */
  private async generateCompliancePDF(
    client: any,
    incidents: any[],
    startDate: Date,
    endDate: Date,
  ): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const chunks: Buffer[] = [];
        const doc = new PDFDocument();

        doc.on('data', (chunk: Buffer) => {
          chunks.push(chunk);
        });

        doc.on('end', () => {
          resolve(Buffer.concat(chunks));
        });

        doc.on('error', reject);

        // ===== COVER PAGE =====
        doc.fontSize(24).font('Helvetica-Bold').text('Incident Compliance Report', {
          align: 'center',
        });
        doc.moveDown();
        doc.fontSize(14).font('Helvetica').text(`Organization: ${client?.name || 'Unknown'}`, {
          align: 'center',
        });
        doc.fontSize(12).text(`Report Period: ${startDate.toDateString()} to ${endDate.toDateString()}`, {
          align: 'center',
        });
        doc.moveDown(2);
        doc.fontSize(12).text('Generated by Helix Incident Management System', {
          align: 'center',
        });
        doc.moveDown();
        doc.fontSize(11).text(`Generated on: ${new Date().toISOString()}`, {
          align: 'center',
        });

        doc.addPage();

        // ===== EXECUTIVE SUMMARY =====
        doc.fontSize(16).font('Helvetica-Bold').text('Executive Summary');
        doc.moveDown(0.5);

        const summary = this.generateExecutiveSummary(incidents);

        doc.fontSize(11).font('Helvetica');
        doc.text(`Total Incidents: ${incidents.length}`);
        doc.text(`Critical Incidents: ${summary.critical}`);
        doc.text(`Warnings: ${summary.warning}`);
        doc.text(`Informational: ${summary.info}`);
        doc.text(`Average Resolution Time: ${summary.avgResolutionTime} minutes`);
        doc.moveDown();

        // ===== SUMMARY TABLE =====
        doc.fontSize(14).font('Helvetica-Bold').text('Incident Summary by Type');
        doc.moveDown(0.5);

        const typeSummary = this.summarizeByType(incidents);

        // Table header
        doc.fontSize(10).font('Helvetica-Bold');
        doc.text('Type');
        doc.text('Count', { continued: true });
        doc.text('Avg Resolution (min)', { continued: true });
        doc.text('Severity');
        doc.moveDown(0.3);

        // Table rows
        doc.font('Helvetica').fontSize(9);
        typeSummary.forEach(row => {
          doc.text(row.type);
          doc.text(row.count.toString(), { continued: true });
          doc.text(row.avgResolution.toFixed(1), { continued: true });
          doc.text(row.severity);
          doc.moveDown(0.2);
        });

        // Add detailed incident list if not too long
        if (incidents.length <= 100) {
          doc.addPage();
          doc.fontSize(14).font('Helvetica-Bold').text('Detailed Incident Log');
          doc.moveDown(0.5);

          doc.fontSize(8).font('Helvetica');

          incidents.forEach((incident, index) => {
            doc.text(`${index + 1}. [${incident.incidentId}]`, { underline: true });
            doc.text(`   Date: ${new Date(incident.detectedAt).toISOString()}`);
            doc.text(`   Type: ${incident.type}`);
            doc.text(`   Severity: ${incident.severity}`);
            doc.text(`   Service: ${incident.service}`);
            doc.text(`   Root Cause: ${incident.rootCause || 'Investigation ongoing'}`);
            doc.text(`   Actions Taken: ${incident.automaticActions?.length || 0} automatic actions`);
            doc.text(
              `   Resolution Time: ${incident.resolutionTime ? `${(incident.resolutionTime / 1000 / 60).toFixed(1)} minutes` : 'Not resolved'}`,
            );
            doc.text(`   Users Notified: ${incident.usersNotified?.length || 0}`);
            doc.moveDown(0.3);
          });
        }

        // ===== COMPLIANCE STATEMENT =====
        doc.addPage();
        doc.fontSize(12).font('Helvetica-Bold').text('Compliance Statement');
        doc.moveDown();

        doc.fontSize(10).font('Helvetica').text(
          'All incidents in this report were logged automatically by Helix without human modification. ' +
          'Each incident includes complete metadata including detection timestamp, automatic response actions, ' +
          'affected systems, and resolution status. No incident data has been altered, redacted, or omitted from this report.',
        );

        doc.moveDown(2);
        doc.fontSize(10).font('Helvetica-Italic').text(
          'This report is suitable for regulatory compliance review including SOC 2, ISO 27001, ' +
          'and other security audit requirements.',
        );

        doc.moveDown(2);
        doc.fontSize(9).text(`Report Hash: ${this.generateReportHash(incidents)}`);

        // Final notes
        doc.moveDown(2);
        doc.fontSize(10).font('Helvetica').text(
          'For questions about this report or the Helix system, please contact your account administrator.',
        );

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Generate executive summary statistics
   */
  private generateExecutiveSummary(incidents: any[]): any {
    const severityGroups = {
      critical: incidents.filter((i: any) => i.severity === 'critical').length,
      warning: incidents.filter((i: any) => i.severity === 'warning').length,
      info: incidents.filter((i: any) => i.severity === 'info').length,
    };

    const resolvedIncidents = incidents.filter((i: any) => i.resolutionTime);
    const avgResolutionTime = resolvedIncidents.length > 0
      ? resolvedIncidents.reduce((sum: number, i: any) => sum + (i.resolutionTime || 0), 0) /
        resolvedIncidents.length /
        1000 /
        60
      : 0;

    return {
      ...severityGroups,
      avgResolutionTime: avgResolutionTime.toFixed(1),
    };
  }

  /**
   * Summarize incidents by type
   */
  private summarizeByType(incidents: any[]): any[] {
    const typeMap: Map<string, any[]> = new Map();

    incidents.forEach((incident: any) => {
      const type = incident.type;
      if (!typeMap.has(type)) {
        typeMap.set(type, []);
      }
      typeMap.get(type)!.push(incident);
    });

    return Array.from(typeMap.entries()).map(([type, typeIncidents]) => {
      const resolved = typeIncidents.filter((i: any) => i.resolutionTime);
      const avgResolution = resolved.length > 0
        ? resolved.reduce((sum: number, i: any) => sum + (i.resolutionTime || 0), 0) /
          resolved.length /
          1000 /
          60
        : 0;

      const severity = typeIncidents[0].severity;

      return {
        type,
        count: typeIncidents.length,
        avgResolution,
        severity,
      };
    });
  }

  /**
   * Generate hash for report integrity
   */
  private generateReportHash(incidents: any[]): string {
    const data = incidents.map(i => `${i.incidentId}:${i.severity}:${i.type}`).join('|');
    const hash = require('crypto').createHash('sha256').update(data).digest('hex');
    return hash.substring(0, 16).toUpperCase();
  }
}
